# eeg_cnn

vocab_size: 3
ffn_embedding_dim: 10

# training

device: cuda
batch_size: 32
warmup_steps: 4000
base_lr: 5e-5
epochs: 10000

run_name: eeg_basic_cnn
# use_ckpt_path: /var/log/thavamount/eeg_ckpts/eeg_lm/eeg_llm.pth
use_ckpt_path: None
save_ckpt_path: /var/log/thavamount/eeg_ckpts/cnn/eeg_basic_cnn
save_every: 100
