# language_model

vocab_size: 29
num_layers: 4
decoder_num_layers: 4
num_heads: 4
num_classes: 4
embedding_dim: 64
decoder_embedding_dim: 64
ffn_hidden_dim: 64
qk_length: 64
value_length: 64
max_length: 2048

encoder_dropout: 0.1
decoder_dropout: 0.1

recon_lambda: 7

# training

device: cpu
batch_size: 32
warmup_steps: 10_000
base_lr: 5.0e-5
epochs: 150_000

# scheduled sampling

min_value: 0.1
k: 55_555

# checkpoints
run_name: lm_4c_8l_09acc
save_every: 5000

# save_ckpt_path: null
save_ckpt_path: /Users/ojasprabhune/Documents/research/NORA/ckpts/lm/lm_4c_8l_09acc

# use_ckpt_path: null
# use_ckpt_path: /Users/ojasprabhune/Documents/research/NORA/ckpts/lm/lm_5c_epoch_15000.pth
use_ckpt_path: /Users/ojasprabhune/Documents/research/NORA/ckpts/lm/lm_4c_8l_epoch_25000.pth

# inference

beam_width: 15
