hyperparameters:
  batch_size: 32
  warmup_steps: 4000
  base_lr: 5e-5
  epochs: 10000
  vocab_size: 512
  num_layers: 4
  num_heads: 4
  embedding_dim: 256
  ffn_hidden_dim: 256
  qk_length: 256
  value_length: 256
  max_length: 2048
  dropout: 0.1
  duration_prediction: True
  lambda_duration: 5
  run_name: log_pos_llm_duration_256_tril_fix_lambda_5
  use_ckpt_path: /var/log/thavamount/eeg_ckpts/hand_lm/log_pos_llm_duration_256_tril_fix_lambda_5_log.pth
  save_ckpt_path: /var/log/thavamount/eeg_ckpts/hand_lm/log_pos_llm_duration_256_tril_fix_lambda_5.pth