# temporal model

stride: 15
val_ratio: 0.2
num_features: 84
d_model: 64
num_heads: 4
num_layers: 2
dropout: 0.3
vocab_size: 4

# training

device: cpu
batch_size: 32
seq_length: 60
warmup_steps: 500
base_lr: 2e-4
epochs: 5000

run_name: temporal
# use_ckpt_path: /var/log/thavamount/eeg_ckpts/eeg_lm/eeg_llm.pth
use_ckpt_path: None
save_ckpt_path: /var/log/thavamount/eeg_ckpts/temporal/temporal
save_every: 200
