# temporal model

stride: 30 # 15
val_ratio: 0.2
num_features: 84
d_model: 128 # 64
num_heads: 8 # 4
num_layers: 4 # 2
dropout: 0.3
vocab_size: 4

# training

device: cpu
batch_size: 32
seq_length: 120 # 90
warmup_steps: 2000
base_lr: 5e-4 # 1e-4
epochs: 500 # 250

run_name: temporal_no_sampler
use_ckpt_path: /var/log/thavamount/eeg_ckpts/temporal/sampler/sampler_big_epoch_150.pth
save_ckpt_path: /var/log/thavamount/eeg_ckpts/temporal/sampler/sampler_big
save_every: 50 # 20
